# Generated by Django 6.0.5 on 2026-06-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
        ('community', '0012_completionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.challenge'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('completion_submitted', 'Completion Submitted'), ('completion_approved', 'Completion Approved'), ('completion_rejected', 'Completion Rejected')], max_length=20),
        ),
    ]
