# Generated by Django 6.0.5 on 2026-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
