from django.urls import path

from accounts.views import FollowToggleView, NotificationListView, NotificationUnreadCountView, ProfilePictureUploadView, UserPostsView, UserPublicProfileView

from .views import (
    ChallengeDetailView,
    ChallengeLeaderboardView,
    ChallengeListCreateView,
    CommentDeleteView,
    CommentListCreateView,
    CompletionRequestReviewView,
    CompletionRequestSubmitView,
    CreatePostView,
    FeedPostsView,
    GlobalPostsView,
    HubCompletionRequestsListView,
    HubCoverUploadView,
    HubDeleteView,
    HubDetailView,
    HubListView,
    HubMemberRemoveView,
    HubMembersView,
    HubPostsView,
    HubUpdateView,
    JoinHubView,
    LeaveHubView,
    MyCompletionRequestView,
    PostMediaUploadView,
    PostValidateView,
    PostValidationsListView,
    RecommendedHubsView,
    SearchView,
    TemplateListView,
    ExploreListView,
    ToggleLikeView,
)

urlpatterns = [
    path("explore/feed/", ExploreListView.as_view(), name="explore-feed"),
    path("users/<int:user_id>/profile/", UserPublicProfileView.as_view(), name="user-profile"),
    path("users/<int:user_id>/profile-picture/", ProfilePictureUploadView.as_view(), name="user-profile-picture"),
    path("users/<int:user_id>/posts/", UserPostsView.as_view(), name="user-posts"),
    path("users/<int:user_id>/follow/", FollowToggleView.as_view(), name="user-follow"),
    path("search/", SearchView.as_view(), name="search"),
    path("templates/", TemplateListView.as_view(), name="templates-list"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="notifications-unread"),
    path("posts/feed/", FeedPostsView.as_view(), name="posts-feed"),
    path("posts/global/", GlobalPostsView.as_view(), name="posts-global"),
    path("posts/", CreatePostView.as_view(), name="posts-create"),
    path("posts/<int:id>/like/", ToggleLikeView.as_view(), name="posts-like-toggle"),
    path("posts/<int:id>/media/", PostMediaUploadView.as_view(), name="posts-media-upload"),
    path("posts/<int:id>/validate/", PostValidateView.as_view(), name="posts-validate"),
    path("posts/<int:id>/validations/", PostValidationsListView.as_view(), name="posts-validations"),
    path("hubs/", HubListView.as_view(), name="hubs-list"),
    path("hubs/<int:id>/", HubDetailView.as_view(), name="hubs-detail"),
    path("hubs/recommended/", RecommendedHubsView.as_view(), name="hubs-recommended"),
    path("hubs/<int:id>/join/", JoinHubView.as_view(), name="hubs-join"),
    path("hubs/<int:id>/leave/", LeaveHubView.as_view(), name="hubs-leave"),
    path("hubs/<int:id>/posts/", HubPostsView.as_view(), name="hubs-posts"),
    path("hubs/<int:id>/cover/", HubCoverUploadView.as_view(), name="hubs-cover-upload"),
    path("hubs/<int:id>/settings/", HubUpdateView.as_view(), name="hubs-update"),
    path("hubs/<int:id>/delete/", HubDeleteView.as_view(), name="hubs-delete"),
    path("hubs/<int:id>/members/", HubMembersView.as_view(), name="hubs-members"),
    path("hubs/<int:id>/members/<int:user_id>/", HubMemberRemoveView.as_view(), name="hubs-member-remove"),
    path("hubs/<int:id>/challenges/", ChallengeListCreateView.as_view(), name="challenges-list"),
    path("challenges/<int:id>/", ChallengeDetailView.as_view(), name="challenge-detail"),
    path("challenges/<int:id>/leaderboard/", ChallengeLeaderboardView.as_view(), name="challenge-leaderboard"),
    path("challenges/<int:id>/completion-request/", CompletionRequestSubmitView.as_view(), name="completion-request-submit"),
    path("challenges/<int:id>/completion-request/mine/", MyCompletionRequestView.as_view(), name="completion-request-mine"),
    path("hubs/<int:id>/completion-requests/", HubCompletionRequestsListView.as_view(), name="hub-completion-requests"),
    path("completion-requests/<int:id>/", CompletionRequestReviewView.as_view(), name="completion-request-review"),
    path("posts/<int:id>/comments/", CommentListCreateView.as_view(), name="post-comments"),
    path("comments/<int:id>/", CommentDeleteView.as_view(), name="comment-delete"),
]
