# Generated by Django 6.0.5 on 2026-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_challenge_challengeprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('progress_update', 'Progress Update'), ('achievement_broadcast', 'Achievement Broadcast'), ('admin_announcement', 'Admin Announcement')], default='regular', max_length=30),
        ),
    ]
