# Generated by Django 6.0.5 on 2026-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='member', max_length=20),
        ),
    ]
