# Generated by Django 6.0.5 on 2026-06-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_alter_socialaccount_provider_userprofile'),
        ('community', '0005_hubmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hubs', to='accounts.interest'),
        ),
    ]
