# Generated by Django 6.0.5 on 2026-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_hub_category_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.AddField(
            model_name='hub',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='hub_covers/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, upload_to='post_media/'),
        ),
    ]
