# Generated by Django 6.0.5 on 2026-06-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_post_hub_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(blank=True, default='', max_length=50)),
                ('entry_increment', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('require_proof_per_entry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('proof_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text'), ('number', 'Number'), ('any', 'Any')], default='any', max_length=10)),
                ('proof_prompt', models.CharField(blank=True, max_length=255)),
                ('is_milestone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeStreakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_days', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('require_proof', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCountProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreakProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_checkins', models.PositiveIntegerField(default=0)),
                ('checkin_calendar', models.JSONField(default=list)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='challengeprogress',
            name='unique_challenge_user_progress',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='target_count',
        ),
        migrations.AddField(
            model_name='challenge',
            name='progress_model',
            field=models.CharField(choices=[('stage', 'Stage-Based'), ('count', 'Count-Based'), ('streak', 'Streak-Based')], default='count', max_length=10),
        ),
        migrations.AddField(
            model_name='challengecountconfig',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_config', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='challengestage',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='challengestreakconfig',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_config', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='usercountprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_progress_entries', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='usercountprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstageprogress',
            name='proof_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.post'),
        ),
        migrations.AddField(
            model_name='userstageprogress',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='community.challengestage'),
        ),
        migrations.AddField(
            model_name='userstageprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstreakprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_progress_entries', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='userstreakprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='challengeprogress',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeprogress',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='challengestage',
            constraint=models.UniqueConstraint(fields=('challenge', 'order_index'), name='unique_challenge_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='usercountprogress',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_count_progress'),
        ),
        migrations.AddConstraint(
            model_name='userstageprogress',
            constraint=models.UniqueConstraint(fields=('user', 'stage'), name='unique_user_stage_progress'),
        ),
        migrations.AddConstraint(
            model_name='userstreakprogress',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_streak_progress'),
        ),
        migrations.DeleteModel(
            name='ChallengeProgress',
        ),
    ]
