# Generated by Django 6.0.5 on 2026-06-16 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_challengecountconfig_challengestage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='peer_validation_threshold',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.challenge'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='linked_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_posts', to='community.challengestage'),
        ),
        migrations.AddField(
            model_name='post',
            name='trusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weighted_validation_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('progress_update', 'Progress Update'), ('achievement_broadcast', 'Achievement Broadcast'), ('admin_announcement', 'Admin Announcement'), ('stage_proof', 'Stage Proof'), ('count_entry', 'Count Entry'), ('streak_checkin', 'Streak Check-in')], default='regular', max_length=30),
        ),
        migrations.CreateModel(
            name='PostValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='community.post')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'validator'), name='unique_post_validator')],
            },
        ),
    ]
