# Generated by Django 6.0.5 on 2026-06-16 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_completionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('finance', 'Finance'), ('learning', 'Learning'), ('reading', 'Reading'), ('mindfulness', 'Mindfulness'), ('creative', 'Creative'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=20)),
                ('progress_model', models.CharField(choices=[('stage', 'Stage-Based'), ('count', 'Count-Based'), ('streak', 'Streak-Based')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_official', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('count_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('count_unit_label', models.CharField(blank=True, default='', max_length=50)),
                ('count_entry_increment', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('streak_target_days', models.PositiveIntegerField(blank=True, null=True)),
                ('streak_frequency', models.CharField(default='daily', max_length=10)),
                ('streak_grace_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('proof_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text'), ('number', 'Number'), ('any', 'Any')], default='any', max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='community.challengetemplate')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
