# Generated by Django 6.0.5 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_seed_official_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecountconfig',
            name='is_cumulative',
            field=models.BooleanField(default=False),
        ),
    ]
